### ISSUE TITLE
Umbraco backend shows errors if page is not published

### ISSUE THREAD

**Issue by SonniTost** [skybrud/Skybrud.Umbraco.Feedback#20]
When a user accesses a node that is not published then Umbraco shows errors.

![image](https://user-images.githubusercontent.com/66302306/219037866-3403146c-5c58-484c-8e0d-8aa2a01f9b09.png)

**Comment by abjerner** [comment]
Hey @SonniTost 

I've just pushed a new release, which among other things, adds support a page specific content app:

https://github.com/skybrud/Skybrud.Umbraco.Feedback/releases/tag/v4.0.0-alpha002

I think updating the package without any changes to your code should fix the content app, but if no, let's talk on Slack.
